
const $=s=>document.querySelector(s);const reports=window.REPORTS||[];const pages=window.SCHOOL_PAGES||[];let active=0;let soundOn=true;
function tone(){if(!soundOn)return;try{const c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.setValueAtTime(540,c.currentTime);o.frequency.exponentialRampToValueAtTime(310,c.currentTime+.28);g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.3);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.31)}catch(e){}}
function init(){const cin=$('#cinema');if(cin&&sessionStorage.getItem('seen')==='yes')cin.classList.add('hide');$('#startBtn')?.addEventListener('click',()=>{tone();cin.classList.add('open');setTimeout(()=>{cin.classList.add('hide');sessionStorage.setItem('seen','yes')},1200)});if(localStorage.getItem('theme')==='dark')document.body.classList.add('dark');$('#themeBtn')?.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light')});$('#menuBtn')?.addEventListener('click',()=>$('#topNav')?.classList.toggle('open'));$('#soundBtn')?.addEventListener('click',e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'🔊':'🔇';tone()});window.addEventListener('scroll',()=>{if(scrollY>650)$('#topBtn')?.classList.add('show');else $('#topBtn')?.classList.remove('show')});$('#topBtn')?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));reveal();renderPortal();renderTabs();renderCarousel();renderGallery();bindClose()}
function reveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x))}
function renderPortal(){if(!$('#portalTabs'))return;$('#portalTabs').innerHTML=reports.slice(0,8).map((r,i)=>`<article class="portal-card" data-go="${i}"><img src="${r.cover}" alt="${r.title}"><div class="overlay"><div><h3>${r.title}</h3></div></div></article>`).join('');document.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>{active=+el.dataset.go;tone();renderTabs();location.hash='tabbed'})}
function renderTabs(){if(!$('#sideTabs')||!$('#tabContent'))return;$('#sideTabs').innerHTML=reports.map((r,i)=>`<button class="tab-btn ${i===active?'active':''}" data-tab="${i}" type="button"><span class="tab-icon">${r.icon}</span><span>${r.title}</span></button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>{const select=()=>{const n=+b.dataset.tab;if(active===n)return;active=n;renderTabs();setTimeout(()=>$('#tabContent')?.scrollIntoView({behavior:'smooth',block:'start'}),60)};b.addEventListener('touchend',e=>{e.preventDefault();select()},{passive:false});b.addEventListener('click',select)});const r=reports[active];const preview=r.pagePaths.slice(0,4);$('#tabContent').innerHTML=`<div class="tab-hero enhanced"><div class="section-cover"><img loading="lazy" decoding="async" src="${r.cover}" alt="${r.title}"><div class="salama-badge"><img loading="lazy" decoding="async" src="assets/characters/salama.jpeg" alt="سلامة"><span>${r.icon}</span></div></div><div class="tab-report"><span class="label">${r.icon} ${r.title}</span><h2>${r.subtitle}</h2><p>${r.report}</p><div class="identity-strip"><span>هوية القسم</span><b>${r.title}</b><em>${r.subtitle}</em></div><div class="tab-actions"><button onclick="openReport()" type="button">عرض التقرير كاملًا</button><button onclick="copyText()" type="button">نسخ التقرير</button><button onclick="window.print()" type="button">طباعة</button></div></div></div><div class="tab-pages compact">${preview.map((p,i)=>`<img loading="lazy" decoding="async" src="${p}" data-src="${p}" alt="صفحة ${r.pages[i]}">`).join('')}</div>${r.pagePaths.length>4?`<button class="more-btn" onclick="openReport()" type="button">عرض كل صفحات هذا القسم</button>`:''}`;bindImages()}
function openReport(){const r=reports[active];tone();$('#reportPanelContent').innerHTML=`<div class="tab-hero enhanced report-view"><div class="section-cover"><img src="${r.cover}" alt="${r.title}"><div class="salama-badge large"><img src="assets/characters/salama.jpeg" alt="سلامة"><span>${r.icon}</span></div></div><div><span class="label">${r.icon} ${r.title}</span><h2>${r.subtitle}</h2><p>${r.report}</p><div class="identity-strip"><span>سلامة تستعرض</span><b>${r.title}</b><em>${r.subtitle}</em></div></div></div><div class="tab-pages">${r.pagePaths.map((p,i)=>`<img loading="lazy" decoding="async" src="${p}" data-src="${p}" alt="صفحة ${r.pages[i]}">`).join('')}</div>`;$('#reportModal').classList.add('open');bindImages()}
function copyText(){navigator.clipboard?.writeText(reports[active].title+'\n'+reports[active].subtitle+'\n\n'+reports[active].report)}
function renderCarousel(){if(!$('#pageCarousel'))return;const picks=[0,1,2,3,4,12,21,27,32,34,44,48];$('#pageCarousel').innerHTML=picks.filter(i=>pages[i]).map(i=>`<div class="page-thumb" data-src="${pages[i]}"><img src="${pages[i]}" alt="صفحة ${i+1}"><b>${i+1}</b></div>`).join('');bindImages()}
function renderGallery(){if(!$('#galleryGrid'))return;function draw(){const q=($('#pageSearch')?.value||'').trim();const list=pages.map((p,i)=>({p,num:i+1})).filter(x=>!q||String(x.num).includes(q));$('#galleryGrid').innerHTML=list.map(x=>`<article class="gallery-item" data-src="${x.p}"><img src="${x.p}" alt="صفحة ${x.num}"><p>صفحة ${x.num}</p></article>`).join('');bindImages()}$('#pageSearch')?.addEventListener('input',draw);draw()}
function bindImages(){document.querySelectorAll('[data-src]').forEach(el=>{if(el.dataset.bound==='1')return;el.dataset.bound='1';const open=e=>{e.stopPropagation();if(e.type==='touchend')e.preventDefault();tone();$('#bigImage').src=el.dataset.src;$('#imageModal').classList.add('open')};el.addEventListener('touchend',open,{passive:false});el.addEventListener('click',open)})}
function bindClose(){$('#closeReport')?.addEventListener('click',()=>$('#reportModal').classList.remove('open'));$('#reportModal')?.addEventListener('click',e=>{if(e.target.id==='reportModal')$('#reportModal').classList.remove('open')});$('#closeImage')?.addEventListener('click',()=>$('#imageModal').classList.remove('open'));$('#imageModal')?.addEventListener('click',e=>{if(e.target.id==='imageModal')$('#imageModal').classList.remove('open')})}
window.openReport=openReport;window.copyText=copyText;init();
// kamel3lom
